- name: Executing all Ansible modules
  hosts: localhost
  become: yes

  vars:
    user_group_map:
      raman: amritsar
      ganeev: bengaluru
    packages: [ 'nginx', 'unzip' ]

  tasks:
    - name: Create Users and groups
      import_tasks: user.yaml

    - name: Create cronjob
      import_tasks: cron.yaml

    - name: Create Website
      import_tasks: webserver.yaml
