- name: Executing all Ansible modules
  hosts: localhost
  become: yes

  vars:
    user_group_map:
      raman: amritsar
      ganeev: bengaluru
    packages: [ 'nginx', 'unzip' ]

  tasks:
    - name: Create Users and groups
      import_tasks: playbooks/user.yaml

    - name: Create cronjob
      import_tasks: playbooks/cron.yaml

    - name: Create Website
      import_tasks: playbooks/webserver.yaml

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
       name: nginx
       state: restarted
