- name: Executing all Ansible modules
  hosts: localhost
  become: yes

  vars:
    user_group_map:
      raman: amritsar
      ganeev: bengaluru

  tasks:
# Create groups and users
    - name: Create groups
      ansible.builtin.group:
        name: "{{ item.value }}"
        state: present
      loop: "{{ user_group_map | dict2items }}"

    - name: Create users
      ansible.builtin.user:
        name: "{{ item.key }}"
        group: "{{ item.value }}"
        create_home: true
      loop: "{{ user_group_map | dict2items }}"

# Create Cron job
    - name: Script file
      ansible.builtin.copy:
        dest: /tmp/script.sh
        mode: '0755'
        content: |
          Sample Script file for cronjob
        owner: ansible
        group: ansible

    - name: Cron job
      ansible.builtin.cron:
        name: Cronjob for testing
        state: absent
        user: root

    - name: Cron job
      ansible.builtin.cron:
        name: Cronjob for testing
        minute: "30"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "1"
        job: "/tmp/script.sh"
        user: ansible